version: '3.8'
services:

  postgres:
    image: postgres:16
    container_name: postgres-tenpo
    restart: always
    environment:
      POSTGRES_DB: challenge_tenpo
      POSTGRES_USER: carlos
      POSTGRES_PASSWORD: carlosgr
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: rcarlosgr/calculation-api:latest
    container_name: postgres-tenpo-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/challenge_tenpo
      SPRING_DATASOURCE_USERNAME: carlos
      SPRING_DATASOURCE_PASSWORD: carlosgr
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
