spring:
  application:
    name: challenge-tenpo
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge_tenpo
    username: postgres
    password: carlosgr
  jpa:
    hibernate:
      ddl-auto: update